# Following Tutorial

In [101]:
import geopandas as gpd
import matplotlib.pyplot as plt
import pandas as pd
import folium
import numpy as np

In [102]:
gb_vol = gpd.read_file("World/Global_Volcano.shp")
w_city = gpd.read_file("World/World_City.shp")
w_country = gpd.read_file("World/World_Country.shp")
w_continent = gpd.read_file("World/World_Continent.shp")
w_rivers = gpd.read_file("World/World_River.shp")
w_mjr_lakes = gpd.read_file("World/World_MajorLake.shp")

In [103]:
m = folium.Map(location=[0, 0], zoom_start=2)
folium.GeoJson(w_city,
               name="City",
               marker = folium.CircleMarker(
                   radius = 4,
                   color = 'black',
                   fill = True,
                   fill_color = 'red',
                   fill_opacity = 0.9
               )).add_to(m)

In [104]:
color_dict = {
    "Africa": "purple",
    "Antarctica": "blue",
    "Asia": "cyan",
    "Australia": "green",
    "Europe": "lightgreen",
    "North America": "orange",
    "Oceania": "brown",
    "South America": "red"
}
def style_function(feature):
    cont = feature["properties"]["CONTINENT"]
    return {
        "fillColor": color_dict.get(cont, "gray"),
        "color": "black",      
        "weight": 1,
        "fillOpacity": 0.25 
    }
folium.GeoJson(
    w_continent,
    name="Continent",
    style_function=style_function
).add_to(m)

In [105]:
folium.Choropleth(
    geo_data=w_country.to_json(),
    data=w_country,
    columns=["COUNTRY", "pop_2023"],
    key_on="feature.properties.COUNTRY",
    fill_color="PuRd",
    fill_opacity=0.7,
    line_opacity=0.5,
    nan_fill_color="gray",
    bins = 6,
    name="Population 2023"
).add_to(m)

In [ ]:
folium.GeoJson(gb_vol,name="Volcanoe").add_to(m)
folium.GeoJson(w_rivers,name="River").add_to(m)
folium.GeoJson(w_mjr_lakes,name="Major Lakes").add_to(m)
folium.LayerControl().add_to(m)
m.save("map1.html")

In [107]:
w_city[w_city['POPULATION'] > 10000000]

,NAME,COUNTRY,POPULATION,CAPITAL,geometry
33,London,UK,11100000,Y,POINT (-0.178 51.48791)
132,Seoul,Korea Rep,15850000,Y,POINT (126.93525 37.54235)
145,Tokyo,Japan,23620000,Y,POINT (139.80919 35.68306)
157,Osaka,Japan,15040000,N,POINT (135.51912 34.63553)
210,Calcutta,India,11100000,N,POINT (88.33422 22.54354)
220,Mexico City,Mexico,14100000,Y,POINT (-99.12757 19.42705)
275,Rio de Janeiro,Brazil,10150000,N,POINT (-43.45518 -22.72157)
276,Sao Paulo,Brazil,15175000,N,POINT (-46.6229 -23.5813)
293,Buenos Aires,Argentina,10750000,Y,POINT (-58.40959 -34.6654)
545,Moskva,Russia,13100000,Y,POINT (37.7 55.75)
548,New York,US,16472000,N,POINT (-74.1 40.75)

In [108]:
w_city[(w_city['POPULATION'] > 10000000) & (w_city['CAPITAL'] == 'Y')]

             NAME    COUNTRY  POPULATION CAPITAL                    geometry
33         London         UK    11100000       Y     POINT (-0.178 51.48791)
132         Seoul  Korea Rep    15850000       Y  POINT (126.93525 37.54235)
145         Tokyo      Japan    23620000       Y  POINT (139.80919 35.68306)
220   Mexico City     Mexico    14100000       Y  POINT (-99.12757 19.42705)
293  Buenos Aires  Argentina    10750000       Y  POINT (-58.40959 -34.6654)
545        Moskva     Russia    13100000       Y          POINT (37.7 55.75)

In [109]:
w_country['PG22_23'] = (w_country['pop_2023']-w_country['pop_2022'])*100/w_country['pop_2022']

In [110]:
w_country.head()

,COUNTRY,ISO,COUNTRYAFF,Shape_Leng,Shape_Area,pop_place,pop_1980,pop_2000,pop_2010,pop_2022,pop_2023,pop_2030,pop_2050,area_km,geometry,PG22_23
0,Afghanistan,AF,Afghanistan,6.110457e+06,9.346494e+11,4,12486631,19542982,28189672,41128771,42239854,50330837,74075234,641902.68,"POLYGON ((61.27655 35.60725, 61.29638 35.62854...",2.701474
1,Albania,AL,Albania,1.271948e+06,5.058670e+10,8,2941651,3182021,2913399,2842321,2832439,2789599,2456472,28654.79,"POLYGON ((19.57083 41.68527, 19.58195 41.69569...",-0.347674
2,Algeria,DZ,Algeria,8.316049e+06,3.014489e+12,12,18739378,30774621,35856344,44903225,45606480,49787283,60001113,2317489.00,"POLYGON ((4.60335 36.88791, 4.63555 36.88638, ...",1.566157
3,American Samoa,AS,United States,6.729120e+04,1.754581e+08,16,32886,58230,54849,44273,43914,41142,33557,163.78,"POLYGON ((-170.7439 -14.37555, -170.74942 -14....",-0.810878
4,Andorra,AD,Andorra,1.171375e+05,9.349956e+08,20,35611,66097,71519,79824,80088,81528,80504,507.16,"POLYGON ((1.44584 42.60194, 1.48653 42.65042, ...",0.330728

# Answer Question

## 1
- **point** — volcano,city
- **line** — river
- **polygon** — country,continent,majorlake

In [111]:
print(gb_vol.geom_type.unique())
print(w_city.geom_type.unique())
print(w_country.geom_type.unique())
print(w_continent.geom_type.unique())
print(w_rivers.geom_type.unique())
print(w_mjr_lakes.geom_type.unique())

['Point']
['Point']
['Polygon' 'MultiPolygon']
['MultiPolygon']
['MultiLineString' 'LineString']
['Polygon' 'MultiPolygon']

## 2
- Volcano in Indonesia: **126**
- Volcano in Philippines,Russia,Mexico,Maxico-Guatemala: **224**
- Volcano in Kenya and have elevation greater than 1500 m: **11**

In [112]:
gb_vol[gb_vol['Country'] == 'Indonesia'].shape[0]

126

In [113]:
A2 = ['Philippines','Russia','Mexico','Maxico-Guatemala']

gb_vol[gb_vol['Country'].isin(A2)].shape[0]

224

In [114]:
gb_vol[(gb_vol['Country'] == 'Kenya') & (gb_vol['Elevation_'] > 1500)].shape[0]

11

## 3
- Majorlake have depth greater than or eqaul to 500 m  and less than 5000 m: **15**
- Name of Majorlake have surf_elev greater than or equal to 1000 m and have depth greater than 2000m : **Lake Baikal,Issyk Kul,Lake Tanganyika,Lake Nyasa**

In [115]:
w_mjr_lakes[w_mjr_lakes['DEPTH'].between(500, 5000, inclusive='left')].shape[0]

15

In [116]:
w_mjr_lakes[(w_mjr_lakes['SURF_ELEV'] >= 1000) & (w_mjr_lakes['DEPTH'] > 2000)]['NAME']

8         Lake Baikal
24          Issyk Kul
35    Lake Tanganyika
36         Lake Nyasa
Name: NAME, dtype: object

## 4
- The two countries with the highest expected population in 2050: <u>India, China</u>
- India's population in 2050 <u>increases</u> from population in 2030 <u>by 10.26%</u>
- China's population in 2050 <u>decreases</u> from population in 2030 <u>by 7.27%</u>

In [117]:
w_country.sort_values(by='pop_2050', ascending=False).head(2)

,COUNTRY,ISO,COUNTRYAFF,Shape_Leng,Shape_Area,pop_place,pop_1980,pop_2000,pop_2010,pop_2022,pop_2023,pop_2030,pop_2050,area_km,geometry,PG22_23
104,India,IN,India,2.051907e+07,3.772218e+12,356,696828385,1059633675,1240613620,1417173173,1428627663,1514994080,1670490596,3152151.22,"MULTIPOLYGON (((68.1978 23.76668, 68.20846 23....",0.808263
47,China,CN,China,3.816869e+07,1.495893e+13,156,982372466,1264099069,1348191368,1425887337,1425671352,1415605906,1312636325,9405607.16,"MULTIPOLYGON (((109.7036 18.19777, 109.67727 1...",-0.015147

In [118]:
w_country.columns

Index(['COUNTRY', 'ISO', 'COUNTRYAFF', 'Shape_Leng', 'Shape_Area', 'pop_place',
       'pop_1980', 'pop_2000', 'pop_2010', 'pop_2022', 'pop_2023', 'pop_2030',
       'pop_2050', 'area_km', 'geometry', 'PG22_23'],
      dtype='object')

In [119]:
w_country['PG50_30'] = (w_country['pop_2050']-w_country['pop_2030'])*100/w_country['pop_2030']
w_country[w_country['COUNTRY'].isin(['India', 'China'])]

,COUNTRY,ISO,COUNTRYAFF,Shape_Leng,Shape_Area,pop_place,pop_1980,pop_2000,pop_2010,pop_2022,pop_2023,pop_2030,pop_2050,area_km,geometry,PG22_23,PG50_30
47,China,CN,China,3.816869e+07,1.495893e+13,156,982372466,1264099069,1348191368,1425887337,1425671352,1415605906,1312636325,9405607.16,"MULTIPOLYGON (((109.7036 18.19777, 109.67727 1...",-0.015147,-7.273887
104,India,IN,India,2.051907e+07,3.772218e+12,356,696828385,1059633675,1240613620,1417173173,1428627663,1514994080,1670490596,3152151.22,"MULTIPOLYGON (((68.1978 23.76668, 68.20846 23....",0.808263,10.263837

## 5 
- Thailand's expected population <u>rank 26th</u> and <u>decreases 5.46</u>

In [120]:
w_country['Rank_2050'] = w_country['pop_2050'].rank(ascending=False)
w_country['PG50_23'] = (w_country['pop_2050']-w_country['pop_2023'])*100/w_country['pop_2023']
w_country[w_country['COUNTRY'] == 'Thailand'][['Rank_2050', 'PG50_23']]

     Rank_2050   PG50_23
223       26.0 -5.461178